name: Build and Test Python App

# Trigger the workflow on pushes to the main branch or pull requests targeting the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define a job named "build_and_test"
  build_and_test:
    # Specify the environment the job runs on
    runs-on: ubuntu-latest

    # Define the steps of the job
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install -r requirements.txt  # Install dependencies

      # Step 4: Run unit tests with pytest
      - name: Run unit tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          pip install pytest  # Install pytest
          pytest tests/  # Run tests in the tests/ directory

      # Step 5: Lint and format code
      - name: Lint and format code
        run: |
          source venv/bin/activate  # Activate the virtual environment
          pip install flake8 black  # Install flake8 and black
          flake8 .  # Lint code
          black --check .  # Check formatting
